package de.asbach.nmaster.gui;



import de.asbach.nmaster.model.Semester;

/*
 * NewJDialog.java
 *
 * Created on 23. August 2008, 14:11
 */



/**
 *
 * @author Benjamin Asbach <my.name at gmail.com>
 */
public class SemesterAddDialog extends javax.swing.JDialog {
    private Semester result;
    
    /** Creates new form NewJDialog */
    public SemesterAddDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ComponentCenterer.centerComponent(this);
        this.getRootPane().setDefaultButton(cmdSave);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSemesterAlias = new javax.swing.JLabel();
        txtSemesterAlias = new javax.swing.JTextField();
        cmdAbort = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblSemesterAlias.setText("Semester Anzeigename:");

        cmdAbort.setText("Abbrechen");
        cmdAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAbortActionPerformed(evt);
            }
        });

        cmdSave.setText("Speichern");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSemesterAlias))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtSemesterAlias, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdAbort)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSemesterAlias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSemesterAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSave)
                    .addComponent(cmdAbort))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
    try{
        result = new Semester(txtSemesterAlias.getText());
    }catch (Exception e){
        result = null;
    }finally{
        dispose();
    }
}//GEN-LAST:event_cmdSaveActionPerformed

private void cmdAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbortActionPerformed
    dispose();
}//GEN-LAST:event_cmdAbortActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAbort;
    private javax.swing.JButton cmdSave;
    private javax.swing.JLabel lblSemesterAlias;
    private javax.swing.JTextField txtSemesterAlias;
    // End of variables declaration//GEN-END:variables

    public Semester getResult(){
        return result;
    }
}
