/*
 * SemsterPanel.java
 *
 * Created on 23. August 2008, 16:31
 */
package de.asbach.nmaster.gui.components;

import de.asbach.nmaster.core.GradeCalculator;
import de.asbach.nmaster.core.GrademasterProperties;
import de.asbach.nmaster.gui.ModuleAddDialog;
import de.asbach.nmaster.model.Module;
import de.asbach.nmaster.model.Semester;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Benjamin Asbach <my.name at gmail.com>
 */
public class SemesterPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 8647842970518342451L;
    private Semester semester;
    private List<RefreshGradeListener> listeners;

    /** Creates new form SemsterPanel */
    public SemesterPanel(Semester s) {
        semester = s;
        listeners = new ArrayList<RefreshGradeListener>();

        initComponents();
        lblSemGrade.setVisible(false);
        lblSemesterGrade.setVisible(false);
        ((AbstractTableModel) tblModules.getModel()).addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent e) {
                doRefresh();

                for (RefreshGradeListener l : listeners) {
                    l.doRefresh();
                }
            }
        });

        doRefresh();

        DefaultTableCellRenderer dtc = new DefaultTableCellRenderer();
        dtc.setHorizontalAlignment(SwingConstants.CENTER);

        /* resize our columns */
        TableColumn c = tblModules.getColumnModel().getColumn(0);
        c.setPreferredWidth(60);
        c.setMaxWidth(60);
        c.setMinWidth(60);
        c.setCellRenderer(dtc);


        c = tblModules.getColumnModel().getColumn(2);
        c.setPreferredWidth(75);
        c.setMaxWidth(75);
        c.setMinWidth(75);
        c.setCellRenderer(dtc);

        c = tblModules.getColumnModel().getColumn(3);
        c.setPreferredWidth(100);
        c.setMaxWidth(100);
        c.setMinWidth(100);
        c.setCellEditor(new EmptyCellEditor());
    }

    public void addRefreshGradeListener(RefreshGradeListener l) {
        listeners.add(l);
    }

    public void removeRefreshGradeListener(RefreshGradeListener l) {
        listeners.remove(l);
    }

    public void doRefresh() {
        double d = GradeCalculator.calculateGradeBySemester(semester);
        final GrademasterProperties p = GrademasterProperties.getInstance();

        String format = "0.0";
        double multiplicator = 10.0;

        if (p.get("precission") != null) {
            StringBuffer sb = new StringBuffer("0.");
            for (int i = 0; i < Integer.valueOf(p.getProperty("precission")); i++) {
                sb.append("0");
            }
            format = sb.toString();

            multiplicator = Math.pow(10, Integer.valueOf(p.getProperty("precission")));
        }

        if (d != 0) {
            DecimalFormat df = new DecimalFormat(format);
            d = Math.round(d * multiplicator) / multiplicator;

            lblSemGrade.setVisible(true);
            lblSemesterGrade.setVisible(true);
            lblSemesterGrade.setText(df.format(d));
        } else {
            lblSemGrade.setVisible(false);
            lblSemesterGrade.setVisible(false);
        }
    }

    public Semester getSemester() {
        return semester;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblModules = new javax.swing.JTable();
        btnNewModule = new javax.swing.JButton();
        btnChangeModule = new javax.swing.JButton();
        btnDeleteModule = new javax.swing.JButton();
        lblSemGrade = new javax.swing.JLabel();
        lblSemesterGrade = new javax.swing.JLabel();

        tblModules.setModel(new SemesterTableModel(semester));
        tblModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblModulesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblModulesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblModules);

        btnNewModule.setText("Neues Modul");
        btnNewModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewModuleActionPerformed(evt);
            }
        });

        btnChangeModule.setText("Modul ändern");
        btnChangeModule.setEnabled(tblModules.getSelectedRowCount() != 0);
        btnChangeModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeModuleActionPerformed(evt);
            }
        });

        btnDeleteModule.setText("Modul löschen");
        btnDeleteModule.setEnabled(tblModules.getSelectedRowCount() != 0);
        btnDeleteModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteModuleActionPerformed(evt);
            }
        });

        lblSemGrade.setText("Notendurchschnitt dieses Semesters:");

        lblSemesterGrade.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSemesterGrade.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSemesterGrade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewModule, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangeModule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteModule)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemGrade)
                    .addComponent(lblSemesterGrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewModule)
                    .addComponent(btnChangeModule)
                    .addComponent(btnDeleteModule))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnDeleteModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteModuleActionPerformed
    Module deleteModule = ((SemesterTableModel) tblModules.getModel()).getModuleAt(tblModules.getSelectedRow());
    if (deleteModule != null) {
        semester.removeModule(deleteModule);
        ((AbstractTableModel) tblModules.getModel()).fireTableDataChanged();
    }

    btnChangeModule.setEnabled(tblModules.getSelectedRowCount() != 0);
    btnDeleteModule.setEnabled(tblModules.getSelectedRowCount() != 0);
}//GEN-LAST:event_btnDeleteModuleActionPerformed

private void btnNewModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewModuleActionPerformed
    ModuleAddDialog dialog = new ModuleAddDialog((JFrame) this.getParent().getParent().getParent().getParent().getParent(), true);
    dialog.setVisible(true);

    Module result = dialog.getResult();
    if (result != null) {
        semester.addModule(result);

        ((AbstractTableModel) tblModules.getModel()).fireTableDataChanged();
    }
}//GEN-LAST:event_btnNewModuleActionPerformed

private void btnChangeModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeModuleActionPerformed
    Module editModule = ((SemesterTableModel) tblModules.getModel()).getModuleAt(tblModules.getSelectedRow());
    ModuleAddDialog dialog = new ModuleAddDialog(null, true, editModule);
    dialog.setVisible(true);

    Module result = dialog.getResult();
    if (result != null) {
        editModule.setModulNumber(result.getModulNumber());
        editModule.setModuleName(result.getModuleName());
        editModule.setCreditPoints(result.getCreditPoints());
        editModule.setGrade(result.getGrade());

        ((AbstractTableModel) tblModules.getModel()).fireTableDataChanged();
    }

    btnChangeModule.setEnabled(tblModules.getSelectedRowCount() != 0);
    btnDeleteModule.setEnabled(tblModules.getSelectedRowCount() != 0);
}//GEN-LAST:event_btnChangeModuleActionPerformed

private void tblModulesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModulesMouseReleased
    btnChangeModule.setEnabled(tblModules.getSelectedRowCount() != 0);
    btnDeleteModule.setEnabled(tblModules.getSelectedRowCount() != 0);
}//GEN-LAST:event_tblModulesMouseReleased

private void tblModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModulesMouseClicked
    if (evt.getClickCount() == 2) {
        Module editModule = ((SemesterTableModel) tblModules.getModel()).getModuleAt(tblModules.getSelectedRow());
        ModuleAddDialog dialog = new ModuleAddDialog(null, true, editModule);
        dialog.setVisible(true);

        Module result = dialog.getResult();
        if (result != null) {
            editModule.setModulNumber(result.getModulNumber());
            editModule.setModuleName(result.getModuleName());
            editModule.setCreditPoints(result.getCreditPoints());
            editModule.setGrade(result.getGrade());

            ((AbstractTableModel) tblModules.getModel()).fireTableDataChanged();
        }

        btnChangeModule.setEnabled(tblModules.getSelectedRowCount() != 0);
        btnDeleteModule.setEnabled(tblModules.getSelectedRowCount() != 0);
    }
}//GEN-LAST:event_tblModulesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeModule;
    private javax.swing.JButton btnDeleteModule;
    private javax.swing.JButton btnNewModule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSemGrade;
    private javax.swing.JLabel lblSemesterGrade;
    private javax.swing.JTable tblModules;
    // End of variables declaration//GEN-END:variables
}
